version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: medods
      MONGO_INITDB_ROOT_PASSWORD: medods
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
    mongo-data: