http:
  port: 8080
  address: ':8080'
  readTimeout: 10s
  writeTimeout: 10s
  shutdownTimeout: 5s

mongo:
  username: 'medods'
  password: 'medods'
  url: 'mongodb://mongo:27017'
  db: 'medods'
  collection: 'token'