basePath: /auth
definitions:
  entity.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handlers.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
      user_guid:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: TestTask for Junior Go Dev
  title: TestTask
  version: "1.0"
paths:
  /token:
    get:
      consumes:
      - application/json
      description: Generates a pair of access and refresh tokens for the given GUID.
      parameters:
      - description: GUID
        in: query
        name: user_guid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.TokenResponse'
        "400":
          description: User GUID is required
          schema:
            type: string
        "405":
          description: Only GET method is allowed
          schema:
            type: string
        "500":
          description: Failed to generate refresh token
          schema:
            type: string
      summary: Generate token pairs
  /token/refresh:
    post:
      consumes:
      - application/json
      description: Generates new access and refresh tokens based on the provided refresh
        token and user GUID.
      parameters:
      - description: Refresh Token Request
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/handlers.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: A new pair of access and refresh tokens
          schema:
            $ref: '#/definitions/entity.TokenResponse'
        "400":
          description: Error decoding request or Invalid refresh_token
          schema:
            type: string
        "405":
          description: Only POST method is allowed
          schema:
            type: string
        "500":
          description: Failed to generate access token or refresh token or Error delete
            data
          schema:
            type: string
      summary: Refresh token
swagger: "2.0"
